exports.recipes = [
  {
    id: 14,
    title: 'No-Knead Artisan Style Bread',
    title_for_url: 'noknead-artisan-style-bread',
    description: 'No-Knead Artisan Style Bread',
    ingredients: '3 cups all-purpose flour\n 1 teaspoon active dry yeast\n 2 teaspoons salt\n 1 2/3 cups warm water (110 degrees F/45 degrees C)\n 1 teaspoon chopped fresh rosemary\n (optional) 1 teaspoon chopped fresh thyme (optional)\n 1 teaspoon chopped fresh sage (optional)',
    steps: 'Combine the flour, yeast, and salt in a large bowl and mix to combine.\n  Add the water and herbs, if using, and mix well.\n  The dough will be very sticky and shaggy-looking.\n  Cover the bowl with plastic wrap and set aside at room temperature for 18 to 24 hours.\n Generously flour a work surface.\n  The dough will have risen and will be covered in bubbles.\n Transfer the dough to the work surface and dust it with flour.\n Fold the dough in half, and then form the dough into a ball by stretching and tucking the edges of the dough underneath the ball.\n Liberally flour a kitchen towel (do not use terrycloth).\n  Place the dough ball on the floured towel.\n  Cover with another floured towel.\n Let the dough rise for about two hours Preheat an oven to 450 degrees F (230 degrees C).\n  Place a lidded Dutch oven or deep heavy duty casserole dish (with lid) into the oven to preheat.\n Carefully remove the hot baking dish from the oven.\n  Remove the lid and gently turn the dough ball into the ungreased baking dish, seam-side up; shake the dish so the dough is more evenly distributed.\n Cover and bake for 30 minutes.\n  Remove the lid and bake until the crust is golden brown, 15 to 20 minutes.\n  Remove the loaf from the baking dish and let it cool on a rack before slicing.',
    keywords: 'no-knead,artisan,bread',
    active: 'TRUE',
    featured_image_name: 'artisan-bread-3.jpg',
    created_at: '2019-07-24 05:05:59+00',
    updated_at: '2019-07-27 22:06:55+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 13,
    title: 'Dutch Oven Whole Wheat Bread',
    title_for_url: 'dutch-oven-whole-wheat-bread',
    description: 'Dutch Oven Whole Wheat Bread.',
    ingredients: '1 1/2 cups warm water\n 1 teaspoon active dry yeast\n 1 teaspoon agave nectar\n 3 cups whole wheat flour\n 1/2 teaspoon salt',
    steps: 'Pour water into a microwave-safe measuring cup and heat in the microwave oven for about 1 minute.\n  Check temperature using a food thermometer to be sure water is no hotter than 100 degrees F (38 degrees C).\n Add yeast and agave; let sit until foamy, about 15 minutes.\n Combine flour and salt in a large bowl.\n  Add yeast mixture; stir to combine and knead a few times.\n  Cover bowl and let dough rise in a warm place until doubled in size, overnight to 18 hours.\n Turn dough out onto a floured surface.\n Knead 5 to 10 times using floured hands.\n  Shape dough into a ball and let rise while oven is preheating.\n Preheat the oven to 450 degrees F (230 degrees C) and place a Dutch oven inside to warm for 30 minutes.\n Use floured hands to carefully drop dough into the hot Dutch oven.\n  Use potholders to place the lid on the Dutch oven.\n Bake in the hot oven for 30 minutes.\n  Uncover Dutch oven and bake until bread is deep golden brown, 10 to 15 minutes more.\n  Remove and let cool.',
    keywords: 'dutch,oven,whole,wheat,bread',
    active: 'TRUE',
    featured_image_name: 'dutch-wheat-bread.jpg',
    created_at: '2019-07-24 05:05:59+00',
    updated_at: '2019-07-27 22:07:58+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 8,
    title: 'Easy, Chewy Flourless Peanut Butter Cookies',
    title_for_url: 'easy-chewy-flourless-peanut-butter-cookies',
    description: 'Easy, Chewy Flourless Peanut Butter Cookies',
    ingredients: '1 cup peanut butter\n 1/2 cup white sugar\n 1/3 cup packed brown sugar\n 1 egg\n 1 teaspoon vanilla extract\n 1/2 teaspoon baking soda\n 1/2 cup semisweet chocolate chips',
    steps: 'Preheat oven to 350 degrees F (175 degrees C). Beat peanut butter, white sugar, and brown sugar together in a large bowl with an electric mixer until smooth. Stir egg, vanilla extract, and baking soda into peanut butter mixture; stir in chocolate chips. Drop mixture by small rounded spoonfuls onto a baking sheet about 2 inches apart. Bake in the preheated oven until cookies are flattened and golden, about 8 minutes.',
    keywords: 'easy,chewy,flourless,peanut,butter,cookies',
    active: 'TRUE',
    featured_image_name: 'peanut-cookies.jpg',
    created_at: '2019-07-24 05:05:56+00',
    updated_at: '2019-07-27 22:37:09+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 9,
    title: 'Ultimate Double Chocolate Cookies',
    title_for_url: 'ultimate-double-chocolate-cookies',
    description: 'Ultimate Double Chocolate Cookies',
    ingredients: '1 pound semisweet chocolate, chopped\n 2 cups all-purpose flour\n 1/2 cup Dutch process cocoa powder\n 2 teaspoons baking powder\n 1 teaspoon salt\n 10 tablespoons unsalted butter\n 1 1/2 cups packed brown sugar\n 1/2 cup white sugar\n 4 eggs\n 2 teaspoons instant coffee granules\n 2 teaspoons vanilla extract',
    steps: 'Preheat the oven to 350 degrees F (175 degrees C). Melt chocolate over a double boiler or in the microwave, stirring occasionally until smooth.  Sift together flour, cocoa, baking powder, and salt; set aside. In a medium bowl, cream butter with white sugar and brown sugar until smooth.  Beat in eggs one at a time, then stir in coffee crystals and vanilla until well blended.  Stir in melted chocolate. Using a wooden spoon, stir in the dry ingredients just until everything comes together. Cover, and let stand for 35 minutes so the chocolate can set up.  Line two cookie sheets with parchment paper.  Roll dough into walnut sized balls, or drop by rounded tablespoonfuls onto the prepared cookie sheets, leaving 2 inches between cookies. Bake for 8 to 10 minutes in the preheated oven.  Cookies will be set, but the centers will still be very soft because of the chocolate.  Allow cookies to cool on the baking sheets for 10 minutes before transferring to wire racks to cool completely.',
    keywords: 'ultimate,chocolate,cookies',
    active: 'TRUE',
    featured_image_name: 'double-chocolate-cookies.jpg',
    created_at: '2019-07-24 05:05:58+00',
    updated_at: '2019-07-27 22:02:24+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 12,
    title: 'Pumpkin Magic Cake with Maple Cinnamon Whipped Cream',
    title_for_url: 'pumpkin-magic-cake-with-maple-cinnamon-whipped-cream',
    description: 'Pumpkin Magic Cake with Maple Cinnamon Whipped Cream.',
    ingredients: '1 cup all-purpose flour 2 tablespoons pumpkin pie spice 1 teaspoon sea salt 1 teaspoon ground cinnamon 1 1/2 cups lukewarm milk 1 cup canned pumpkin 2 teaspoons vanilla extract 4 eggs, at room temperature, separated 1 cup white sugar 1/4 cup brown sugar 1 tablespoon water 1/2 cup unsalted butter, melted 1 teaspoon cream of tartar ***Maple Cinnamon Whipped Cream:*** 1 1/4 cups heavy whipping cream 1/4 cup maple syrup 1/2 teaspoon ground cinnamon 1 pinch sea salt',
    steps: 'Preheat oven to 325 degrees F (165 degrees C). Grease an 8-inch baking pan. Whisk flour, pumpkin pie spice, 1 teaspoon salt, and 1 teaspoon cinnamon together in a bowl. Combine milk, pumpkin, and vanilla extract in a bowl. Place egg yolks, white sugar, brown sugar, and water in the bowl of a stand mixer.  Beat on high speed until creamy. Reduce speed to low; add butter. Increase speed to medium; beat until light and fluffy.  Reduce speed to low and add flour mixture in 3 batches, blending thoroughly after each addition and scraping down the sides of the bowl. Stir milk-pumpkin mixture slowly into the mixture until just combined; transfer to a separate bowl. Clean and dry out the bowl and beaters. Beat egg whites and cream of tartar on high speed until stiff peaks form. Fold 3/4 of the egg white mixture into the pumpkin mixture using a spatula; pour into the remaining egg whites, folding mixture in slowly until batter is smooth but still light and fluffy. Pour batter into the prepared pan. Bake in the preheated oven until edges are set and center still jiggles slightly, about 50 minutes. Let cool completely, at least 30 minutes. Beat heavy cream, maple syrup, 1/2 teaspoon cinnamon, and 1 pinch salt together in a bowl using an electric mixer until soft peaks form. Spread over cooled cake.',
    keywords: 'pumpkin,cake,cinnamon,cream',
    active: 'TRUE',
    featured_image_name: 'pumpkin-cake.jpg',
    created_at: '2019-07-24 05:05:58+00',
    updated_at: '2019-07-27 22:07:30+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 15,
    title: 'Amish White Bread',
    title_for_url: 'amish-white-bread',
    description: 'Amish White Bread.',
    ingredients: '2 cups warm water (110 degrees F/ 45 degrees C) 2/3 cup white sugar 1 1/2 tablespoons active dry yeast 1 1/2 teaspoons salt 1/4 cup vegetable oil',
    steps: 'In a large bowl, dissolve the sugar in warm water, and then stir in yeast.  Allow to proof until yeast resembles a creamy foam. Mix salt and oil into the yeast.  Mix in flour one cup at a time.  Knead dough on a lightly floured surface until smooth.  Place in a well oiled bowl, and turn dough to coat.  Cover with a damp cloth.  Allow to rise until doubled in bulk, about 1 hour. Punch dough down. Knead for a few minutes, and divide in half.  Shape into loaves, and place into two well oiled 9x5 inch loaf pans.  Allow to rise for 30 minutes, or until dough has risen 1 inch above pans. Bake at 350 degrees F (175 degrees C) for 30 minutes.',
    keywords: 'amish,bread',
    active: 'TRUE',
    featured_image_name: 'amish-bread-2.jpg',
    created_at: '2019-07-24 05:05:59+00',
    updated_at: '2019-07-27 22:08:08+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 16,
    title: 'Cardamom and Espresso Chocolate Chip Cookies',
    title_for_url: 'cardamom-and-espresso-chocolate-chip-cookies',
    description: 'Cardamom and Espresso Chocolate Chip Cookies.',
    ingredients: '3 1/4 cups all-purpose flour\n 1 teaspoon baking powder\n 1 teaspoon baking soda\n 1 teaspoon ground cardamom\n 1/2 teaspoon ground cinnamon\n 1/2 teaspoon salt\n 1 1/2 cups brown sugar, firmly packed\n 1 cup unsalted butter, softened 1/2 cup white sugar\n 2 large eggs, at room temperature\n 2 tablespoons instant espresso powder\n 1 tablespoon vanilla extract\n 1 (12 ounce) bag semisweet chocolate chips',
    steps: 'Preheat the oven to 350 degrees F (175 degrees C).  Line 2 baking sheets with parchment paper. Whisk flour, baking powder, baking soda, cardamom, cinnamon, and salt together in a bowl. Cream brown sugar, butter, and white sugar together in a bowl until fluffy.  Beat in eggs 1 at a time until thoroughly combined.  Mix in instant espresso powder and vanilla extract. Mix flour mixture into the butter mixture until just combined; do not overmix.  Fold in chocolate chips. Drop dough by the tablespoon onto the prepared baking sheets about 2 inches apart. Bake in the preheated oven until edges of cookies are set, 10 to 15 minutes.  Cool cookies on the pans 2 to 3 minutes before transferring to a wire rack to cool completely.',
    keywords: 'cookies,chocolate',
    active: 'TRUE',
    featured_image_name: 'chococookies.jpg',
    created_at: '2019-07-24 05:06:00+00',
    updated_at: '2019-07-27 22:08:23+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 18,
    title: 'Creamy Rice Pudding',
    title_for_url: 'creamy-rice-pudding',
    description: 'The best Creamy Rice Pudding ever!',
    ingredients: '1 1/2 cups white rice cooked 2 cups milk divided 1/3 cup sugar pinch salt 1 egg 2/3 cup raisins 1 tablespoon butter 1/2 teaspoon vanilla cinnamon nutmeg',
    steps: 'Mix the cooked rice, 1 1/2 cups milk, sugar and salt. Cook uncovered over medium heat for about 15-20 minutes.  Whisk egg and remaining milk in a bowl.  Add about 1 cup of the hot rice mixture to the egg while stirring. Stir the egg mixture and raisins into the rice. Cook 2 minutes more. Remove from heat and stir in butter and vanilla. Serve warm and garnish with whipped cream and a sprinkle of nutmeg and cinnamon.',
    keywords: 'creamy,rice,pudding',
    active: 'TRUE',
    featured_image_name: 'creamy-rice-pudding.jpg',
    created_at: '2019-08-01 02:02:02+00',
    updated_at: '2019-08-01 02:02:02+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 19,
    title: 'Super rounded bread',
    title_for_url: 'super-rounded-bread',
    description: 'Super rounded bread',
    ingredients: '1 1/2 cups warm water (95 F to 110 F) 2 1/4 teaspoons or 1 package (1/4 ounce) active dry yeast 1/2 cup milk 1 tablespoon sugar, coconut sugar, or raw sugar 2 teaspoons salt or sea salt 1/3 cup canola oil, coconut oil, or shortening About 4 1/2 cups bread flour Optional: egg white or milk for brushing on the loaf 1 tablespoon butter (melted)',
    steps: 'In a large bowl, mix the warm water and yeast. Add the milk, sugar, salt, and oil and stir to combine.  Add in enough bread flour to make a dough that follows the spoon around the bowl. Turn the dough out onto a lightly floured surface and knead it for 8 minutes, adding more bread flour as needed until the dough is firm and smooth to the touch. Place the dough in a medium greased bowl.  Turn dough over in the bowl so that the top is also lightly greased.  Cover with clean cloth and let rise in warm, draft-free place for 1 hour. Punch down the dough. Turn the dough out onto a lightly floured surface and knead it for about 5 minutes or until the bubbles are out of the bread.  Shape the dough into a round loaf and place it in a greased 1 1/2-quart round casserole dish.  Cover and let rise in a warm, draft-free place for 45 minutes or until doubled in size. Preheat oven to 375 F.  With a sharp knife or razor, slash the top of the bread. For a glossy top, brush an egg white on top of the loaf, or brush loaf with milk before baking to produce a dark, shiny crust.  Bake the bread for 45 minutes or until the bread sounds hollow when the top is tapped. Remove the bread from the casserole dish and let cool on a rack.',
    keywords: 'bread,easy,classic',
    active: 'TRUE',
    featured_image_name: 'super-rounded-bread.jpg',
    created_at: '2019-08-04 23:35:21+00',
    updated_at: '2019-08-04 23:35:21+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 20,
    title: 'Burger Bread',
    title_for_url: 'burger-bread',
    description: 'Burger Bread',
    ingredients: '2 tablespoons active dry yeast 1 cup plus 2 tablespoons warm water (110° to 115°) 1/3 cup vegetable oil 1/4 cup sugar 1 large egg 1 teaspoon salt 3 to 3-1/2 cups all-purpose flour',
    steps: 'In a large bowl, dissolve yeast in warm water.  Add oil and sugar; let stand for 5 minutes.  Add the egg, salt, and enough flour to form a soft dough. Turn onto a floured surface; knead until smooth and elastic, about 3-5 minutes. Do not let rise. Divide into 12 pieces; shape each into a ball.  Place 3 in. apart on greased baking sheets. Cover and let rest for 10 minutes.  Bake at 425° for 8-12 minutes or until golden brown.  Remove from pans to wire racks to cool.',
    keywords: 'burguer, bread, classic',
    active: 'TRUE',
    featured_image_name: 'burger-bread.jpg',
    created_at: '2019-08-05 00:21:05+00',
    updated_at: '2019-08-05 00:21:05+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 21,
    title: 'Peanut Butter Cookies',
    title_for_url: 'peanut-butter-cookies',
    description: 'Peanut Butter Cookies',
    ingredients: '1 cup butter, softened 1 cup creamy peanut butter 1 cup sugar 1 cup packed brown sugar 2 large eggs, room temperature 1 cup all-purpose flour 1 teaspoon baking soda 1/2 teaspoon baking powder 1 cup semisweet chocolate chips 1 cup quick-cooking oats 1 cup sweetened shredded coconut 1 cup chopped pecans or walnuts 1 cup raisins',
    steps: 'Preheat oven to 350°.  In a large bowl, cream butter, peanut butter, and sugars until blended.  Beat in eggs.  In another bowl, whisk flour, baking soda, and baking powder; gradually beat into creamed mixture.  Stir in chocolate chips, oatmeal, coconut, pecans, and raisins. Drop dough by tablespoonfuls 3 in. apart onto greased baking sheets.  Bake until golden brown, 12-15 minutes. Cool on pans 5 minutes.  Remove to wire racks to cool completely.',
    keywords: 'peanut, butter, cookies',
    active: 'TRUE',
    featured_image_name: 'peanut-butter-cookies-2.jpg',
    created_at: '2019-08-05 00:35:05+00',
    updated_at: '2019-08-05 00:35:05+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 22,
    title: 'Parmesan cheese scones',
    title_for_url: 'parmesan-cheese-scones',
    description: 'Parmesan cheese scones',
    ingredients: '2 cups flour\n 4 teaspoons baking powder\n 1/2 cup grated Parmesan cheese\n 1/3 cup oil or butter\n 2/3 cup milk',
    steps: "Preheat oven to 350 degrees F (175 degrees C). Mix the oil and milk Mix the flour with the baking powder and the grated cheese.  Incorporate all and continue mixing. Mix with your hands until you get a moist but firm dough, it doesn't have to be dry We do not use kneading stick, but we are stretching with the fingers the dough until it is about finger thick, and with a glass or mold, we cut circles. We place in a previously oiled roasting pan with a little separation between each one. Baked about 20 minutes",
    keywords: 'parmesan, cheese, scones',
    active: 'TRUE',
    featured_image_name: 'parmesan-cheese-scones.jpg',
    created_at: '2019-08-05 10:52:57+00',
    updated_at: '2019-08-05 10:54:54+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 23,
    title: 'Garlic and oregano bread suitable for celiacs',
    title_for_url: 'garlic-and-oregano-bread-suitable-for-celiacs',
    description: 'Garlic and oregano bread suitable for celiacs',
    ingredients: '2 cups premix\n 2 teaspoon baking powder suitable for coeliacs\n 3 large garlic cloves\n 1 tablespoon oregano\n 3 tablespoons olive oil\n 1/2 cup butter\n 1 pinch of sugar\n 1 egg\n Water\n pinch of salt (optional)',
    steps: 'Crush the garlic and mix with the olive oil and oregano. Reserve. Sift the premix, baking powder, sugar, and salt. Add the butter and the olive oil mixture to the premix. Knead until all the ingredients are integrated. Then add the water and continue kneading for about 10 minutes until the dough does not stick to your hands and has elastic texture. Form a ball with the dough and cover with a clean dry cloth. Let stand for one hour. Preheat the oven to 400 F for 10 minutes. During this time, return to the dough and adding a little flour over it, stretch it again and knead it until it forms the bread you want to prepare. Beat the egg and with a brush paint all the bread on top, this will give it a nice color. Finally, make the mold and put the bread on the mold and bake for 15 to 20 minutes.',
    keywords: 'garlic,oregano,celiacs',
    active: 'TRUE',
    featured_image_name: 'garlic-oregano-bread.jpg',
    created_at: '2019-08-07 12:39:47+00',
    updated_at: '2019-08-07 12:49:16+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 17,
    title: 'Pizza dough. Easy to cook!',
    title_for_url: 'pizza-dough-easy-to-cook',
    description: 'Pizza dough. Easy to cook!',
    ingredients: '300g (10oz) strong white flour 1/2 teaspoon salt 7g (1/4 oz) sachet fast-action yeast 200ml (1/3 pint) warm water 15ml (1 tbsp) olive oil',
    steps: "Preheat the oven to Gas Mark 9, 240°C, fan 220°C. Tip the flour, salt and yeast into a large mixing bowl.  Pour over the water and oil and, using a metal spoon, mix together until you have a sticky dough Dust the work surface with more flour, then tip out the dough. Knead until the dough starts to feel elastic and smooth, about 10 minutes. Clean and lightly oil the mixing bowl, and then return the dough to it.  Cover the bowl with a sheet of clingfilm coated in a little oil to stop the dough from sticking.  Leave in a warm place until the dough has doubled in size, about 1 hour. Lightly flour 2 baking sheets and the work surface.  Knock the air out of the dough by punching it down, and then divide it into 2 pieces. Use a lightly floured rolling pin or your fingers, to press out the dough into two thin circles. If you're pressing out the dough, start with a ball of dough and flatten it using your palms, then press the edges away with your fingers, turning the dough round as you go. Eventually you'll end up with a nice round circle.  Carefully lift the circle onto a baking sheet, and spread out with your fingers until about 30cm (12in) wide. Repeat. Spoon over the sauce, leaving a border of about 1cm (1⁄2in).  Tear the mozzarella into pieces and scatter over the pizza, along with any toppings.  Drizzle over a little oil, and bake for 12-15 minutes, or until the base is crisp.",
    keywords: 'pizza,classic,easy',
    active: 'TRUE',
    featured_image_name: 'classic-pizza.jpg',
    created_at: '2019-07-31 23:17:47+00',
    updated_at: '2019-08-11 08:34:05+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 24,
    title: 'Oatmeal and orange bread (with sweetener)',
    title_for_url: 'oatmeal-and-orange-bread-with-sweetener',
    description: 'Oatmeal and orange bread with sweetener',
    ingredients: '1 cup oatmeal\n 2 cups flour\n 2 teaspoons baking powder\n 1/4 cup sweetener\n 1 egg\n 1 teaspoon vanilla\n 1 cup unsweetened orange juice',
    steps: 'Preheat oven to 350 F (180 C) In a bowl mix the oatmeal, flour and baking powder In another bowl mix the egg, vanilla and sweetener Then join both mixtures in the bowl where we put the egg. Add the orange juice. It should be a squeaky mix. Put some oil in a pudding and spread with a napkin. Bake for 20 to 25 minutes.',
    keywords: 'oatmeal, orange, bread',
    active: 'TRUE',
    featured_image_name: 'oatmeal-and-orange-bread.jpg',
    created_at: '2019-08-14 14:55:54+00',
    updated_at: '2019-08-14 14:55:54+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 25,
    title: 'Pita bread (Arabic bread)',
    title_for_url: 'pita-bread-arabic-bread',
    description: 'Pita bread (Arabic bread)',
    ingredients: '2 cups flour 3 teaspoon instant yeast 4 teaspoon olive oil 1 teaspoon of sugar 10 gr. Salt 1 cup of warm water',
    steps: 'Place the yeast, sugar and a little water in a bowl and let them stand for 5 minutes. Make a crown with the flour in a bowl, add the mixture with the yeast, salt, oil and the rest of the water. Knead by hand until a compact dough forms. Spread the dough on a well-floured surface and work it until it is thin and elastic to the touch. Place the dough in a bowl, cover it with a dishcloth and let it stand until it doubles its volume. Press the dough with the hand fist to extract the air. Divide the dough into 12 equal portions, let the muffins rest for a moment, then stretch each of them, and with the help of a roller form circles 5 mm thick. Place in greased baking sheets with a little oil and take them to a preheated oven at 250 degrees for ten minutes. Once the pieces of bread are taken out of the oven, they are immediately put between two tea towels so that it takes moisture and does not get hard.',
    keywords: 'pita,bread,arabic',
    active: 'TRUE',
    featured_image_name: 'pita-bread.jpg',
    created_at: '2019-08-14 20:09:36+00',
    updated_at: '2019-08-14 20:09:36+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 26,
    title: 'Cornstarch cookies (Maizena)',
    title_for_url: 'cornstarch-cookies-maizena',
    description: 'Cornstarch cookies (Maizena)',
    ingredients: '1 cup of flour\n 1 cup cornstarch\n 1/2 cup of sugar\n 2 eggs\n 1 teaspoon vanilla\n 1/4 cup butter\n 1 tablespoon baking powder\n lemon zest',
    steps: 'Heat the oven to 400F (200C) Melt the butter a little to leave it ointment and mix well with the rest of the ingredients Mix the butter with the sugar and vanilla Add the two eggs and mix well Mix the flour, cornstarch, and powder and bake Gradually add to the mixture we already have butter, eggs, etc. We add a little lemon zest. The dough should remain as mashed potatoes. If necessary add some milk or water Place the dough in a roasting pan with butter paper and crush a little Bake during 15 to 20 minutes',
    keywords: 'cornstarch, cookies, maizena',
    active: 'TRUE',
    featured_image_name: 'cornstarch-cookies.jpg',
    created_at: '2019-08-14 22:26:02+00',
    updated_at: '2019-08-14 22:26:02+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 27,
    title: 'Chococookies',
    title_for_url: 'chococookies',
    description: 'Chococookies',
    ingredients: '200g softened butter 300g soft brown sugar 2 tsp vanilla extract 2 eggs 300g self-raising flour 80g cocoa powder 1 tsp baking powder 300g choc chips',
    steps: 'Preheat oven to 180C Cream butter and sugar until light and fluffy, then beat in vanilla extract and eggs in a separate bowl sift flour, cocoa, and baking powder together. Add flour mix to the creamed mix in stages( a third at a time) mix well. fold in choc chips until just combined. Spoon a tablespoon of the mixture on to a baking tray and just let it drop off the spoon, repeat until you have used up all the cookie mixture. Bake in preheated oven for 12 minutes, when you remove the cookies from the oven they will still be soft, leave to cool completely on the baking tray, where they will continue to cook slightly when they are completely cold.',
    keywords: 'chocolate,cookies,chococookies',
    active: 'TRUE',
    featured_image_name: 'chococookies2.jpg',
    created_at: '2019-08-15 00:23:29+00',
    updated_at: '2019-08-15 00:23:29+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 28,
    title: 'Spinach ricotta pie',
    title_for_url: 'spinach-ricotta-pie',
    description: 'Spinach ricotta pie',
    ingredients: '2 sheets puff pastry or use a shortcrust pastry or empanada dough 20 oz frozen spinach 566g (2 x 10oz packets) 1 onion small, or 1/2 large 2 cloves garlic 1/2 tbsp olive oil 1/2 tsp nutmeg 1 cup ricotta 240g 1 cup mozzarella 120g 1/2 cup parmesan 6 eggs',
    steps: 'Lightly oil/butter the inside of your pie dish. Roll out one piece of pastry to approx 1/8in/3mm thick (or a bit thicker, as you prefer). Turn over your pie dish and use the top to cut the top layer for the pie. Set this aside. Roll out the other piece of pastry, adding in the scraps from before if needed to make large enough, and use this to line the pie dish. Trim the edges.  Defrost the spinach according to packet instructions and squeeze out excess liquid.  Preheat oven to 350F/175C. Finely dice the onion and garlic. Warm the oil in a medium skillet over medium heat and add the onion. Cook a couple of minutes until softening then add the garlic. Cook a couple more minutes until onion is translucent.  Add the spinach and nutmeg to the onion and stir well. Feel free to add a little salt and pepper as well, if you like. Set the pan aside to cool.  Mix the ricotta, mozzarella, parmesan and 1 egg in a bowl. Add the cooled spinach mixture and mix well. Fill the pie dish and spread evenly.  Use the back of a spoon to make 5 indents in the filling - you will probably need to make them deeper than you might think - then crack an egg into each of them. Brush around the edge of the bottom pastry layer with water then carefully put the top layer of pastry over the pie. Press together the edges and put two slits as air holes in the middle. Lightly brush the top with milk.  Bake the pie for approximately 50 minutes until golden brown. Allow cooling a little before slicing.',
    keywords: 'spinach,ricotta,pie',
    active: 'TRUE',
    featured_image_name: 'spinach-ricotta-pie.jpg',
    created_at: '2019-08-15 00:39:33+00',
    updated_at: '2019-08-15 00:39:33+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 29,
    title: 'French lemon yogurt cake',
    title_for_url: 'french-lemon-yogurt-cake',
    description: 'French lemon yogurt cake',
    ingredients: '1 1/2 cups all-purpose flour 210g plain flour 2 tsp baking powder 1/4 tsp salt 1 cup sugar 200g 1 lemon zest (ie from 1 lemon) 3/4 cup plain yogurt 180ml 3 eggs 1/4 tsp vanilla extract 1/4 cup vegetable oil 60ml, or other plain oil eg safflower, canola 1/4 cup lemon olive oil 60ml, or additional veg oil',
    steps: 'Preheat the oven to 350F/175C. Lightly oil and line a standard loaf pan (8 1/2" x 4 1/4"). Combine the flour, salt and baking powder in a medium bowl and whisk together. In a large bowl, rub the lemon zest into the sugar in to help it release the oils. You should get patches that become slightly moist. Add the yogurt, eggs, and vanilla to the lemony sugar and whisk until blended. Gradually add the flour mixture as well and mix in. Pour in the oil(s) and blend until combined. Pour the batter into the lined loaf pan and smooth off the top. Bake for approx 50-55 minutes until the loaf is golden on top and a skewer comes out clean. Leave to cool around 5 minutes before loosening from the pan and carefully taking the loaf out. Continue to cool in a cooling rack.',
    keywords: 'french,lemon,yogurt,cake',
    active: 'TRUE',
    featured_image_name: 'french-lemon-yogurt-cake.jpg',
    created_at: '2019-08-15 01:15:56+00',
    updated_at: '2019-08-15 01:15:56+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 30,
    title: 'Cheese Crackers',
    title_for_url: 'cheese-crackers',
    description: 'Cheese Crackers',
    ingredients: '8 oz  shredded cheddar cheese (225 g) 4 tablespoons  unsalted butter, room temperature 1 teaspoon  salt 1 cup  flour (125 g) 2 tablespoons of ice water',
    steps: 'Preheat oven to 350˚F (180˚C). Using a hand mixer or standing mixer, combine cheese, butter, and salt in a large bowl. Once combined, mix in the flour and add the ice water one tablespoon at a time. The dough should hold together but crumble apart if you break it up in your hand. If it seems too dry, add a little more ice water. Separate dough into two halves and pack together into discs. Wrap in parchment paper and chill in the refrigerator for 30 minutes. Roll out dough to ⅛ of an inch (½ cm), pinching the cracks on the ends. Cut into 1-inch x 1 inch (2 ½ x 2 ½ cm) squares and pierce a hole in the middle of each square for ventilation during baking. Place the separated crackers on a parchment paper-lined baking sheet. Bake for 13 minutes, or until golden brown.',
    keywords: 'cheese,crackers,quick',
    active: 'TRUE',
    featured_image_name: 'cheese-crackers.jpg',
    created_at: '2019-08-15 14:34:11+00',
    updated_at: '2019-08-15 14:34:11+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 32,
    title: 'Focaccia bread',
    title_for_url: 'focaccia-bread',
    description: 'Easy focaccia bread',
    ingredients: '3 cups all-purpose flour 1 envelope (2 1/4 teaspoons) rapid rise or fast-acting yeast 1 tablespoon sugar 1 teaspoon salt 1 2/3 cups very warm water — between 120°-130°F 4 tablespoons olive oil — divided 1 tablespoon Italian seasoning 1/2 teaspoon salt 1/2 teaspoon pepper',
    steps: 'Preheat oven to 375°F. Grease a 9x13-inch pan with nonstick cooking spray or oil. Mix flour, yeast, sugar, and salt in a large bowl.  Add 2 tablespoons olive oil to the water, then add the wet ingredients to the dry, stirring until well mixed.  Cover and let rise until doubled, about 30 minutes. Using the handle of a wooden spoon, poke multiple holes into the dough. Drizzle remaining 2 tablespoons of olive oil over dough.  Sprinkle with Italian seasoning, salt, and pepper. Cover again and let rise an additional 15 minutes.  Bake 30 to 35 minutes until lightly browned. Cool slightly and slice into pieces.',
    keywords: 'focaccia,bread,easy',
    active: 'TRUE',
    featured_image_name: 'focaccia-1.jpg',
    created_at: '2019-08-17 12:19:22+00',
    updated_at: '2019-08-17 12:19:22+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 31,
    title: 'Chocolate chip cookies',
    title_for_url: 'chocolate-chip-cookies',
    description: 'One of the best recipes of chocolate chip cookies. This dough requires chilling.',
    ingredients: '1/2 cup (113g) unsalted butter, melted  1/3 cup (66 g) granulated sugar  1/2 cup (104g) packed light brown sugar  1 large egg  1 teaspoon (5ml) vanilla extract  1/2 teaspoon baking soda  1/2 teaspoon salt  1 1/2 cups (186g) all-purpose flour  1 1/2 cups (255g) chocolate chips (semi-sweet or milk)',
    steps: 'Place melted butter in the bowl of a stand mixer fitted with the paddle attachment (or a large bowl if using a hand mixer).  Add granulated and brown sugars and mix on low speed until the mixture is smooth.  Mix in egg and vanilla extract and mix on medium speed until combined. Mix in baking soda and salt, then slowly mix in flour and mix just until the batter is smooth and comes together. Be sure to scrape the sides of the bowl during mixing. Slowly mix in chocolate chips. Line a cookie sheet with a silicone baking mat or parchment paper. Scoop 2 tablespoon balls of dough onto the cookie sheet. Spacing doesn’t matter because you will be chilling the dough. Cover with plastic wrap and chill for at least 2 hours. Preheat oven to 350°F. Line a second cookie sheet with parchment paper or a silicone baking mat. Remove the chilled cookie dough balls from the refrigerator and space them 2-inches apart on the cookie sheets. Bake (2 tablespoons sized cookies) for 11-15 minutes, or until the edges are a light golden and the tops are no longer glossy. Let cool on the cookie sheets at least 10 minutes before removing.',
    keywords: 'chocolate,cookies,sweet',
    active: 'TRUE',
    featured_image_name: 'chocolate-chip-cookies.jpg',
    created_at: '2019-08-17 11:05:08+00',
    updated_at: '2019-08-17 11:07:31+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 33,
    title: 'Mexican cornbread',
    title_for_url: 'mexican-cornbread',
    description: 'Mexican cornbread',
    ingredients: '1 15 ounces box Simply Homemade® Cornbread mix  2/3 cup milk  1/2 cup unsalted butter — melted  1 large egg  1 cup shredded cheese — cheddar, jack, or Mexican blend  2 medium jalapeños — diced small',
    steps: 'Preheat oven to 375°F. Spray an 8-inch baking pan with non-stick cooking spray. Whisk together cornbread mix, milk, melted butter, and egg until moistened.  Stir in cheese and jalapeños. Pour mixture into prepared pan.  If desired, sprinkle with more cheese. Bake for 25-30 minutes or until a toothpick comes out clean.  Let sit 5 minutes before slicing and serving',
    keywords: 'mexican,corn,bread',
    active: 'TRUE',
    featured_image_name: 'mexican-cornbread.jpg',
    created_at: '2019-08-18 17:15:53+00',
    updated_at: '2019-08-18 17:15:53+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 34,
    title: 'Creme Brulee',
    title_for_url: 'creme-brulee',
    description: 'Creame Brulee',
    ingredients: '1 box Instant Vanilla Pudding Mix (3.4-ounce size) 1 cup nonfat milk 3/4 cup heavy whipping cream 1 teaspoon vanilla bean paste  4 tablespoons sugar',
    steps: 'Whisk together pudding mix, milk, and heavy whipping cream.  Add vanilla bean paste and whisk until smooth. Pour into 4 creme brûlée dishes or small ramekins.  Chill until set, about 30 minutes or up to overnight. Torch method: sprinkle each dish with a tablespoon of sugar. Torch until browned being careful not to burn the sugar. Oven method: preheat the broiler to high. Place ramekins on a cookie sheet and place them under the broiler (close to the flame for just minute or two, watching the whole time until sugar is browned. Stove method: place 1/2 cup sugar in a small saucepan. Heat without stirring. Once it starts to turn to liquid, stir with a wooden spoon, being careful not to get it on the sides of the pan, until the sugar turns to crystals than to liquid again, and turns a light amber color. Drizzle some onto each creme brûlée. Note: this sugar hardens more than it does with the torch. Err on the light side of adding it to the top - you don’t need the entire amount but it’s hard to make less than 1/2 cup - and be cautious eating it.',
    keywords: 'creme,brulee,easy',
    active: 'TRUE',
    featured_image_name: 'creme-brulee-2.jpg',
    created_at: '2019-08-19 12:50:08+00',
    updated_at: '2019-08-19 12:50:47+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 35,
    title: 'Big Chocolate Chip Cookies',
    title_for_url: 'big-chocolate-chip-cookies',
    description: 'Big Chocolate Chip Cookies. This dough requires chilling.',
    ingredients: '1 cup unsalted butter, melted 2/3 cup granulated sugar 1 cup light brown sugar, packed 2 large eggs 2 teaspoons vanilla extract 1 teaspoon baking soda 1 teaspoon salt 3 cups all-purpose flour 3 cups chocolate chips (semi-sweet or milk)',
    steps: 'Place melted butter in the bowl of a stand mixer fitted with the paddle attachment (or a large bowl if using a hand mixer).  Add granulated and brown sugars and mix on low speed until the mixture is smooth.  Mix in egg and vanilla extract and mix on medium speed until combined. Mix in baking soda and salt, then slowly mix in flour and mix just until the batter is smooth and comes together.  Be sure to scrape the sides of the bowl during mixing. Slowly mix in chocolate chips. Line a cookie sheet with a silicone baking mat or parchment paper. Scoop 1/4 cup balls of dough onto the cookie sheet. Spacing doesn’t matter because you will be chilling the dough.  Cover with plastic wrap and chill for at least 2 hours or overnight. Preheat oven to 350°F. Line a second cookie sheet with parchment paper or a silicone baking mat. Remove the chilled cookie dough balls from the refrigerator and space them 4-inches apart on the cookie sheets. I baked 4 per cookie sheet.  Bake one cookie sheet at a time in the center of the oven, rotating the pan halfway through baking. Only bake for about 10-15 minutes (the top will start to brown almost like a biscuit). Note: These will not get cooked and "done" all the way through - they will stay gooey. Let cool at least 10 minutes on cookie sheet before removing. Store in an airtight container for up to 3 days or freeze for up to one month.',
    keywords: 'chocolate,chips,cookies',
    active: 'TRUE',
    featured_image_name: 'big-chocolate-chip-cookies-1.jpg',
    created_at: '2019-08-19 12:56:10+00',
    updated_at: '2019-08-19 12:56:10+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 36,
    title: 'Chocolate butter cake',
    title_for_url: 'chocolate-butter-cake',
    description: 'Chocolate Butter Cake',
    ingredients: '1 box chocolate cake mix — about 15-16 ounces 1 box instant chocolate pudding mix — about 3.4 ounces 4 large eggs 1/2 cup unsalted Challenge Butter — melted 1 cup milk 1 teaspoon butter extract — optional 1/4 cup unsalted Challenge Butter 3/4 cup granulated sugar 1 tablespoon unsweetened cocoa powder 2 tablespoons water 1 teaspoon vanilla extract',
    steps: 'Preheat oven to 350°F. Spray a bundt pan with nonstick cooking spray (I like using the kind with flour in it). Whisk together cake mix and pudding mix in a large bowl. Add eggs, melted butter, milk, and extract if using. Whisk until mostly smooth. Pour batter into prepared pan. Bake for 30-40 minutes, or until a toothpick comes out mostly clean from the center of the cake. As soon as the cake comes out of the oven, make the sauce: melt butter in a small saucepan over medium heat. Add the sugar, cocoa, and water. Stir and bring to a boil, cooking until the sugar is dissolved and the sauce is no longer grainy, about 2-3 minutes. Remove from heat and stir in vanilla. Even though the cake is still hot, we’re going to remove it from the pan. Invert the cake onto a rack set over a cookie sheet. Using a long skewer, poke several small holes all over the cake. Carefully pour hot chocolate butter sauce over the cake, allowing any extra to drip onto the cookie sheet under the rack. (If you want, you can scoop this extra sauce up off the pan and drizzle it over the cake again.) Let the cake cool then transfer to a serving plate. Store loosely covered for up to 3 days.',
    keywords: 'chocolate,butter,cake',
    active: 'TRUE',
    featured_image_name: 'chocolate-butter-cake.jpg',
    created_at: '2019-08-21 14:50:39+00',
    updated_at: '2019-08-21 14:50:39+00',
    user_id: 1,
    category_name: '',
    prep_time_seo: '',
    cook_time_seo: '',
    total_time_seo: '',
    prep_time: '',
    cook_time: '',
    total_time: '',
    cuisine: '',
    yield: ''
  },
  {
    id: 37,
    title: 'Banana Pudding',
    title_for_url: 'banana-pudding',
    description: 'Easy banana pudding',
    ingredients: '1 (3.4 ounces) box Instant vanilla pudding mix 1 1/4 cups milk 1 (14 ounces) can sweetened condensed milk — (not fat-free) 1 teaspoon vanilla extract 1/4 teaspoon banana extract — optional 2 cups heavy whipping cream 1/4 cup powdered sugar 2 packages Chessman butter cookies — or other similar sized butter cookie or shortbread cookie 5-6 medium bananas — sliced',
    steps: 'Whisk pudding mix, milk, sweetened condensed milk, and both extracts in a large bowl until smooth. Set aside to set for 5 minutes. Make whipping cream by beating heavy whipping cream with powdered sugar with a hand or stand mixer until stiff peaks form. Place one layer of cookies in the bottom of a 9x13-inch baking dish (about 24 cookies, depending on what kind you’re using), breaking some to fit if needed. Fold half the whipped cream into the pudding mixture. Pour half on top of the cookies. Cover with banana slices, then the rest of the pudding mixture. Spread the remaining whipped cream on top of the pudding and top with crumbled cookies. Cover and chill at least one hour before serving. Best eaten within 24 hours or up to 2 days (the bananas may discolor after a day or so).',
    keywords: 'easy,banana,pudding',
    active: 'TRUE',
    featured_image_name: 'banana-pudding.jpg',
    created_at: '2019-08-22 14:11:48+00',
    updated_at: '2019-08-23 13:36:21+00',
    user_id: 1,
    category_name: 'General',
    prep_time_seo: 'PT10M',
    cook_time_seo: 'PT20M',
    total_time_seo: 'PT30M',
    prep_time: '10 minutes',
    cook_time: '20 minutes',
    total_time: '30 minutes',
    cuisine: 'American',
    yield: '5 servings'
  },
  {
    id: 38,
    title: 'Peanut Butter Frosting',
    title_for_url: 'peanut-butter-frosting',
    description: 'Peanut Butter Frosting',
    ingredients: '1 cup creamy peanut butter 1/2 cup unsalted butter — softened 4 cups powdered sugar 1/4 teaspoon salt 1 teaspoon vanilla extract 6 tablespoons heavy whipping cream',
    steps: 'Beat peanut butter and butter in a large bowl with a hand mixer until creamy (or in the bowl of a stand mixer fitted with the paddle attachment). Mix in 1 cup of powdered sugar at a time, slowly, until mixture is crumbly. Add salt and vanilla and mix, then add 1 tablespoon of heavy whipping cream. Beat frosting until smooth, adding more heavy whipping cream until you reach the desired consistency (I always add 6 tablespoons). Pipe or frost as desired.',
    keywords: 'peanut, butter, frosting',
    active: 'TRUE',
    featured_image_name: 'peanut-butter-frosting-2.jpg',
    created_at: '2019-08-23 13:47:44+00',
    updated_at: '2019-08-23 13:50:31+00',
    user_id: 1,
    category_name: 'General',
    prep_time_seo: 'PT5M',
    cook_time_seo: 'PT5M',
    total_time_seo: 'PT10M',
    prep_time: '5 minutes',
    cook_time: 5,
    total_time: '10 minutes',
    cuisine: 'American',
    yield: '24 servings'
  },
  {
    id: 39,
    title: 'Vegan brownie',
    title_for_url: 'vegan-brownie',
    description: 'Best vegan brownie!',
    ingredients: '4 tablespoons ground flax 1/2 cup water 1/2 cup vegan butter (earth balance brand), melted *see instructions 1 cup granulated sugar 1 cup brown sugar, lightly packed 1 tablespoon pure vanilla extract 1 cup all purpose flour 1 cup unsweetened cocoa powder 1/2 teaspoon salt 1 teaspoon baking powder 1 cup non-dairy chocolate chips OR roughly chopped chocolate pieces',
    steps: 'Make the flax eggs by stirring the ground flax and water in a small bowl. Set aside to thicken. Preheat the oven to 350 degrees F and line a 7 x 11 pan with parchment paper. Melt the vegan butter (earth balance brand preferred), and measure 1/2 cup. I do this by microwaving the vegan butter in a glass measuring cup, in 30 second intervals, until melted. In a large bowl, whisk the melted vegan butter and sugars together. Add the flax eggs and vanilla, whisk until evenly combined. Over the same large bowl, sift in the flour and cocoa powder. Add the salt and baking powder and stir with a large wooden spoon until just combined, do not over mix.  Fold in half of the chocolate chips. Pour the batter into the prepared pan and smooth out the top with a spoon or your hands. Sprinkle the rest of the chocolate chips on top of the batter. Bake for 35-40 minutes. The brownies may still be bubbling and not look done, but they will firm up a lot as they cool. Remove from the oven, allow to cool in the pan for 15 minutes, then pull the brownies out, using the parchment paper and let cool for another 15-30 minutes before slicing and serving.',
    keywords: 'vegan,brownie,easy',
    active: 'TRUE',
    featured_image_name: 'vegan-brownie.jpg',
    created_at: '2019-09-22 21:24:10+00',
    updated_at: '2019-09-22 21:24:18+00',
    user_id: 1,
    category_name: 'General',
    prep_time_seo: 'PT10M',
    cook_time_seo: 'PT40M',
    total_time_seo: 'PT50M',
    prep_time: '10 minutes',
    cook_time: '40 minutes',
    total_time: '50 minutes',
    cuisine: 'American',
    yield: '5 servings'
  },
  {
    id: 75,
    title: 'Gluten-free chickpea flour cookies',
    title_for_url: 'glutenfree-chickpea-flour-cookies',
    description: 'Gluten-free chickpea flour cookies',
    ingredients: '2 t chickpea flour 1/2 t cassava starch 1 tbsp coconut oil 3 tbsp olive oil / sunflower / corn 1/2 t cold water Salt',
    steps: 'In a bowl we mix all the dry ingredients. We add the oils, water and flavors that we are going to add. These have curry, paprika, pepper, grated garlic, a little rosemary and parsley, sesame and sunflower We form the dough. It should be sticky, because chickpea flour continues to absorb liquid and after a while it becomes more malleable Let the dough rest 30 minutes, stretch with cassava starch and cut the cookies with a thickness of 3 mm approx Bake 20 minutes at 180 degrees. When they are dry but still barely soft we take them out',
    keywords: 'gluten-free,cookies,chickpea',
    active: 'TRUE',
    featured_image_name: 'gluten-free-chickpea-flour-cookies.jpg',
    created_at: '2019-12-19 13:50:03+00',
    updated_at: '2019-12-19 13:50:03+00',
    user_id: 1,
    category_name: 'General',
    prep_time_seo: 'PT20M',
    cook_time_seo: 'PT30M',
    total_time_seo: 'PT50M',
    prep_time: '20 minutes',
    cook_time: '30 minutes',
    total_time: '50 minutes',
    cuisine: 'American',
    yield: '5 servings'
  },
  {
    id: 72,
    title: 'The best New York pizza recipe',
    title_for_url: 'the-best-new-york-pizza-recipe',
    description: 'The best New York pizza recipe. Source: feelingfoodish.com',
    ingredients: '6 cups flour all purpose\n 2 1/4 cups  water\n 17.4 oz (493 grams or mls)\n Luke cold 1 teaspoon\n (1 tsp) instant dry yeast\n (3.5 grams) 2.5 teaspoons (2.5 tsp) salt\n (15.6 grams) 2 teaspoons (2 tsp) sugar\n (7.8 grams) 1 tablespoon (1 tbs) olive oil (11.8 ml)',
    steps: "Place water in mixing bowl. In a separate bowl, mix salt and yeast (and sugar if using) into flour Combine flour/salt/yeast mixture into water and mix until all the flour has been incorporated. After flour has been totally incorporated, add oil and knead for about 4 to 5 minutes (see note) Test final dough temperature, which should ideally be between high 70s to low 80s (optional) Divide dough into 4 equal pieces (using a digital scale if possible; each ball should weigh 11.5 oz [~326 grams]), shape into a ball, and place in greased, sealed quart-sized container or oiled/greased freezer bag and refrigerate overnight or up to 72 hours (After much experimenting, I have concluded that I like 3 days best but day 2 is good too). The following day, remove your dough balls within 1 hour or less of baking and allow the dough to come to room temperature. (the dough will tend to blister more if the dough has not been allowed to come to room temperature however, I often bake coldish dough without problems, just some bubbling) In the meantime, place your pizza stone in oven and preheat at 550 degrees (depending on thickness of your stone and your oven's power) for at least 1 hour Open each dough ball using care not to degas, transfer to a pre-floured pizza peel (or on parchment paper), and top with your favorite sauce, cheese, or other toppings. Transfer pizza from peel to oven or slide parchment paper onto preheated pizza pan/stone and bake for 4 to 6 minutes each until browned on top and cheese has melted but not burned.",
    keywords: 'pizza, new-york, italian',
    active: 'TRUE',
    featured_image_name: 'new-york-pizza-2.jpg',
    created_at: '2019-12-16 03:48:47+00',
    updated_at: '2019-12-16 03:54:13+00',
    user_id: 1,
    category_name: 'General',
    prep_time_seo: 'PT20M',
    cook_time_seo: 'PT30M',
    total_time_seo: 'PT50M',
    prep_time: '20 minutes',
    cook_time: '30 minutes',
    total_time: '50 minutes',
    cuisine: 'American',
    yield: '5 servings'
  },
  {
    id: 74,
    title: 'Simple cookies',
    title_for_url: 'simple-cookies',
    description: 'Simple cookies',
    ingredients: '2 cups flour 0000\n 1 teaspoon baking powder\n 1 cup of sugar\n juice of a squeezed orange\n 2 squirts oil 1 teaspoon vanilla',
    steps: 'Preheat oven to 180 degrees Place the flour together with the baking powder, sugar, oil, and mix. Then slowly add the orange juice and vanilla. In case you keep sticking on your fingers, add cornstarch. Mold the cookies Place in a roasting pan with butter and flour Bake for approximately 10 minutes if we make them thin. They will be ready when they take a pale golden brown. Let cool about 15 minutes before removing from the source',
    keywords: 'simple,cookies,easy',
    active: 'TRUE',
    featured_image_name: 'simple-cookies-2.jpg',
    created_at: '2019-12-17 12:29:31+00',
    updated_at: '2019-12-17 12:33:45+00',
    user_id: 1,
    category_name: 'General',
    prep_time_seo: 'PT20M',
    cook_time_seo: 'PT30M',
    total_time_seo: 'PT50M',
    prep_time: '20 minutes',
    cook_time: '30 minutes',
    total_time: '50 minutes',
    cuisine: 'American',
    yield: '5 servings'
  },
  {
    id: 73,
    title: 'Sweet Scones without eggs',
    title_for_url: 'sweet-scones-without-eggs',
    description: 'Sweet scones without eggs.',
    ingredients: '270 gr of flour\n 100 g butter\n 3 spoonfuls of sugar\n half teaspoon salt\n 4 teaspoons baking powder\n 8 tablespoons milk',
    steps: 'Sift together flour, baking powder, salt, and sugar. Add the cold butter and undo it with a fork. The milk is added and kneaded lightly to join the dough. Stretch 2 cm. of thickness. Cut with a round pasta cutter. Bake 200 degrees approximately 10 minutes.',
    keywords: 'sweet,scones,easy',
    active: 'TRUE',
    featured_image_name: 'sweet-scones.jpg',
    created_at: '2019-12-17 12:24:09+00',
    updated_at: '2019-12-17 12:34:07+00',
    user_id: 1,
    category_name: 'General',
    prep_time_seo: 'PT20M',
    cook_time_seo: 'PT30M',
    total_time_seo: 'PT50M',
    prep_time: '20 minutes',
    cook_time: '30 minutes',
    total_time: '50 minutes',
    cuisine: 'American',
    yield: '5 servings'
  },
  {
    id: 76,
    title: 'Fluffy Vanilla Cake',
    title_for_url: 'fluffy-vanilla-cake',
    description: 'Fluffy Vanilla Cake',
    ingredients: '4 eggs\n2 cups of sugar\n 1/2 cup milk\n 2 cups flour\n 2 teaspoons\n baking powder\n Salt\n 1 teaspoon of vanilla',
    steps: 'Separate egg whites from egg yolks. \nBeat the yolks with 1 cup of sugar. \nWarm the milk and add it\n Continue beating and add flour, baking powder and salt.\n In another bowl beat the egg whites to snow and add the other cup of sugar.\n Add vanilla to egg whites to snow.\n Incorporate the egg whites with enveloping movements into the yolk mixture.\n Grease and flour a baking sheet.\n Pour the preparation into the mold.\n Bring the Vanilla Cake to a moderate oven for approximately 20 minutes at 400 degrees fahrenheit',
    keywords: 'fluffy,vanilla,cake',
    active: 'TRUE',
    featured_image_name: 'fluffy-vanilla-cake.jpg',
    created_at: '2019-12-22 01:53:59+00',
    updated_at: '2019-12-22 01:54:17+00',
    user_id: 1,
    category_name: 'General',
    prep_time_seo: 'PT20M',
    cook_time_seo: 'PT30M',
    total_time_seo: 'PT50M',
    prep_time: '20 minutes',
    cook_time: '30 minutes',
    total_time: '50 minutes',
    cuisine: 'American',
    yield: '5 servings'
  }
]
